name: Check URLs in Changed Files

on: [pull_request, push, workflow_dispatch]

jobs:  
  urlchecks:
    name: check-urls
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v4
    
    - id: files
#      uses: jitterbit/get-changed-files@v1 ### Hasn't been updated to Node16
      uses: masesgroup/retrieve-changed-files@v3
      with:
        format: 'csv'

    # We maintain the list of the URLs excluded from checking in a separate file so that we can use
    # it in multiple workflows, while easily maintaining consistency.
    - name: Read exclude-urls list
      id: excludeurls
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.github/workflows/exclude-urls.txt

    # We maintain the list of the file excluded from checking too
    - name: Read exclude-files list
      id: excludefiles
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.github/workflows/exclude-files.txt
        
    # Run URL checks
    - name: URLs-checker
      uses: urlstechie/urlchecker-action@0.0.34
      with:
        # only include the changed files
        include_files: ${{ steps.files.outputs.added_modified }}
        # Use common exclude list read in above
        exclude_urls: ${{ steps.excludeurls.outputs.content }}
        exclude_files: ${{ steps.excludefiles.outputs.content }}
        timeout: 10
        retry_count: 3
        print_all: true
        verbose: true
